#' Classify Veg type with respect to geese forage
#'
#' Classify the veg types from the detailed ones ALMaSS uses into categories
#' matching the ones that are scored in the field
#' 
#' This function is designed to be used in combination with 'sapply' 
#' 
#' @param VegTypeCombo character A string combined from VegType and VegPhase 
#' separated by '-'
#' @return The vegtype matching the one scored in the field
#' @export
ClassifyVegType = function(VegTypeCombo) {
  switch(EXPR = VegTypeCombo,
# Grass  
             'Undefined-2' = 'Grass',  # a special case with permanent types
             'Undefined-3' = 'Grass',  # a special case with permanent types
    'CloverGrassGrazed1-2' = 'Grass',
    'CloverGrassGrazed2-2' = 'Grass',
    'CloverGrassGrazed1-3' = 'Grass',
 'OWinterWheatUndersown-2' = 'Grass',
           'OSeedGrass1-3' = 'Grass',
           'OSeedGrass2-3' = 'Grass',
            'SeedGrass2-3' = 'Grass',
            'SeedGrass2-2' = 'Grass',
           'OSeedGrass1-0' = 'Grass',
           'OSeedGrass2-0' = 'Grass',
            'SeedGrass2-0' = 'Grass',
            'SeedGrass1-3' = 'Grass',
            'SeedGrass1-0' = 'Grass',
   'OCloverGrassGrazed2-0' = 'Grass',
   'OCloverGrassGrazed1-0' = 'Grass',
           'OSeedGrass1-2' = 'Grass',
            'SeedGrass1-2' = 'Grass',
           'OSeedGrass2-2' = 'Grass',
   'OCloverGrassGrazed1-2' = 'Grass',
   'OCloverGrassGrazed1-3' = 'Grass',
    'CloverGrassGrazed1-0' = 'Grass',
    'CloverGrassGrazed2-0' = 'Grass',
   'OCloverGrassGrazed2-2' = 'Grass',
# Rape:
            'WinterRape-0' = 'Rape',
            'WinterRape-2' = 'Rape',
            'WinterRape-3' = 'Rape',
# WinterCereal
          'SpringBarley-1' = 'WinterCereal',
           'WinterWheat-2' = 'WinterCereal',
  'SprBarleyCloverGrass-1' = 'WinterCereal',
             'WinterRye-2' = 'WinterCereal',
 'OBarleyPeaCloverGrass-2' = 'WinterCereal',
                 'OOats-2' = 'WinterCereal',
                 'OOats-1' = 'WinterCereal',
            'OWinterRye-2' = 'WinterCereal',
                  'Oats-1' = 'WinterCereal',
        'OSBarleySilage-2' = 'WinterCereal',
              'OCarrots-1' = 'WinterCereal',
         'OSpringBarley-2' = 'WinterCereal',
         'OSpringBarley-1' = 'WinterCereal',
            'OTriticale-2' = 'WinterCereal',
          'WinterBarley-2' = 'WinterCereal',
             'Triticale-2' = 'WinterCereal',
    'SpringBarleySilage-1' = 'WinterCereal',
 'OBarleyPeaCloverGrass-1' = 'WinterCereal',
            'WinterRape-1' = 'WinterCereal',
           'WinterWheat-1' = 'WinterCereal',
  'SprBarleyCloverGrass-2' = 'WinterCereal',
          'WinterBarley-1' = 'WinterCereal',
 'OWinterWheatUndersown-1' = 'WinterCereal',
            'OWinterRye-1' = 'WinterCereal',
             'WinterRye-1' = 'WinterCereal',
             'Undefined-0' = 'WinterCereal',
           'WinterWheat-0' = 'WinterCereal',
  'SprBarleyCloverGrass-0' = 'WinterCereal',
 'OBarleyPeaCloverGrass-0' = 'WinterCereal',
                 'OOats-0' = 'WinterCereal',
            'OWinterRye-0' = 'WinterCereal',
          'SpringBarley-0' = 'WinterCereal',
          'WinterBarley-0' = 'WinterCereal',
             'WinterRye-0' = 'WinterCereal',
    'SpringBarleySilage-0' = 'WinterCereal',
         'OSpringBarley-0' = 'WinterCereal',
            'OFieldPeas-0' = 'WinterCereal',
        'OSBarleySilage-0' = 'WinterCereal',
          'OMaizeSilage-0' = 'WinterCereal',
 'OWinterWheatUndersown-0' = 'WinterCereal',
          'SpringBarley-2' = 'WinterCereal',
    'SpringBarleySilage-2' = 'WinterCereal',
        'OSBarleySilage-1' = 'WinterCereal',
            'OTriticale-1' = 'WinterCereal',
             'Triticale-1' = 'WinterCereal',
             'Triticale-0' = 'WinterCereal',
            'OTriticale-0' = 'WinterCereal',
# Stubble:
          'WinterBarley-3' = 'Stubble',
 'OBarleyPeaCloverGrass-3' = 'Stubble',
  'SprBarleyCloverGrass-3' = 'Stubble',
    'SpringBarleySilage-3' = 'Stubble',
        'OSBarleySilage-3' = 'Stubble',
            'OWinterRye-3' = 'Stubble',
             'WinterRye-3' = 'Stubble',
         'OSpringBarley-3' = 'Stubble',
          'SpringBarley-3' = 'Stubble',
           'WinterWheat-3' = 'Stubble',
                 'OOats-3' = 'Stubble',
                  'Oats-3' = 'Stubble',
            'OTriticale-3' = 'Stubble',
 'OWinterWheatUndersown-3' = 'Stubble',
             'Triticale-3' = 'Stubble',
          'OMaizeSilage-3' = 'Stubble',
           'MaizeSilage-3' = 'Stubble',
#Maize:
           'MaizeSilage-0' = 'Maize',
           'MaizeSilage-1' = 'Maize',
           'MaizeSilage-2' = 'Maize',
           'MaizeSilage-3' = 'Maize',
          'OMaizeSilage-1' = 'Maize',
          'OMaizeSilage-2' = 'Maize',
          'OMaizeSilage-3' = 'Maize',
#Default:
          'Unknown')
}